### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by Djerry-h** [KellyGong/SparseGAD#1]
您的代码貌似有点问题，我没有跑通，请问是我这边的问题还是？

**Comment by Djerry-h** [comment]
您的代码貌似在utils文件的第151行报错以下问题：
TypeError: _sparse_sum() received an invalid combination of arguments - got (SparseMatrix, int), but expected one of:
 * (Tensor input)
 * (Tensor input, *, torch.dtype dtype)
 * (Tensor input, tuple of ints dim)
      didn't match because some of the arguments have invalid types: (SparseMatrix, int)
 * (Tensor input, tuple of ints dim, *, torch.dtype dtype)
 不知道是否是我pytorch或者dgl版本的问题？期待您的回复！

**Comment by KellyGong** [comment]
应该是pytorch版本的问题，您试一下pytorch 1.10.1版本看看

**Comment by Djerry-h** [comment]
> 应该是pytorch版本的问题，您试一下pytorch 1.10.1版本看看

谢谢您！
